title: Finn's Place
description: J&J Brand Manager pursuing degree in Data Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boolies354.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Finn (Yoon Ho) Nam
author-image:   2.jpg
author-job:     Brand Manager
author-email:   boolies354@gmail.com # Add your email for contant form.
author-twitter: # Add your twitter account
about-author:   Brand Manager located in Seoul currently pursuing degree in Data Science. Plus a freelance DJ. Striving to become something bigger.

# Social settings
social-twitter:   
social-facebook:
social-github:    
social-pinterest: 
social-instagram: yooono._.b
social-youtube:
social-vk:   
social-linkedin: finn-yoon-ho-nam-7a5983114

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
